version: '4.54'

services:
  mysql:
    image: mysql:8.3.0
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    container_name: mock-api-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: mock_api_db
      MYSQL_USER: mock_user
      MYSQL_PASSWORD: 123456
      MYSQL_LOWER_CASE_TABLE_NAMES: 0
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
