version: "4.55"

services:
  postgresql:
    image: bitnami/postgresql:latest
    container_name: wind-api-postgresql
    environment:
      - POSTGRESQL_USERNAME=wind_user
      - POSTGRESQL_PASSWORD=123123
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgresql_data:/bitnami/postgresql

  redis:
    image: redis:8.4.0
    container_name: wind-api-redis
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data

  rabbitmq:
    image: rabbitmq:4.2
    container_name: wind-api-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq
